version: 2

sources:
  - name: raw
    schema: public
    database: sql_practice
    
    tables:
      - name: customers
      - name: orders

models: 
  - name: stg_customers
    description: "Cleaned customer data"
    
    columns: 
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: fct_customer_revenue
        description: "Customer revenue aggregation"
